name: Run API Tests (Rest Assured)

on:
  schedule:
    # Toda sexta-feira às 12:00 BR
    - cron: '0 15 * * 5'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'

      - name: Run API Tests
        run: mvn test