name: Run API Tests (Rest Assured)

on:
  schedule:
    # Toda sexta-feira às 12:00 BR
    - cron: '0 15 * * 5'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'

      - name: Build with Maven
        run: mvn clean install