name: Run API Tests (Rest Assured)

on:
  schedule:
    # Toda sexta-feira às 12:00
    - cron: '0 15 * * 5'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'

      - name: Run API Tests
        run: mvn test